### PR TITLE
Add support for linux

### PR DESCRIPTION
**Pull request by Albert24GG**
I thought it would be nice for this program to be more cross-platform so I ported it to linux. It works more or less the same way it does on windows, but with elf files instead of pe files, and, of course, the signatures and offsets are different. I added configs in `config.rs` to determine at compile time all the necessary platform-dependent configuration. Currently, I have added a few signatures in `config_linux.json` that seem to be working and I am going to add all of them eventually. Please let me know if there is something I should change. Thanks!

### CODE REVIEW

**Comment by Albert24GG** [comment]
Thanks! For the new code base do you intend to add linux support? If you want to, maybe I can help with porting it.

**Comment by a2x** [comment]
Yes, I plan to now thanks to your work :)

I'd be grateful for that but unfortunately, the dev branch is still likely to suffer major breaking changes so there isn't much point as of now.

Unfortunately, I don't have a lot of time at the moment to work on this project but soon, I hope to resolve the current issues and migrate the main branch to it.

I'll just leave this open for now.

**Comment by a2x** [comment]
Sorry for the delay :sweat_smile:

I plan to install Linux tomorrow and finally make a start on this.

**Comment by Albert24GG** [comment]
> Sorry for the delay 😅
> 
> I plan to install Linux tomorrow and finally make a start on this.

Nice! Let me know if you need any help with it.

**Comment by a2x** [comment]
Let me know if you're happy with this so I can close this PR.

**Comment by Albert24GG** [comment]
> Let me know if you're happy with this so I can close this PR.

Yeah, this seems all right to me, thanks! I wanted to mention that in my branch there are some function signatures missing, the ones that seemed a little more difficult to find, and I did not have time to search for them deeper as of now. If you want to, when the dev branch gets merged I will check to see if I can do any improvements/add missing stuff. 
Another thing just out of curiosity: Does github count commits that reference pull requests as contribution? This is the first time I see this type of commit and I did not find info online about this.

**Comment by a2x** [comment]
Cool, thanks!

To answer your question, I'm not entirely sure, but I believe that commits that are part of unmerged pull requests aren't counted even if I add you as a co-author to the commit (which I did). I'll have to double-check that.

**Comment by Albert24GG** [comment]
> Didn't want your contribution to go to waste :)

Omg, thanks a lot! I'll se how I can contribute further to this project. Keep up the good work! :))

**Pull request merged**
